In [1]:
import pandas as pd

In [2]:
df_call_details = pd.read_csv('call details.csv')

In [3]:
df_call_log=pd.read_csv('call log.csv')

In [4]:
df_call_details.shape

(600, 5)

In [39]:
df_call_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   callID                 600 non-null    object
 1   callDurationInSeconds  600 non-null    int64
 2   agentsGradeLevel       600 non-null    object
 3   callType               600 non-null    object
 4   callEndedByAgent       600 non-null    bool
dtypes: bool(1), int64(1), object(3)
memory usage: 19.5+ KB

In [30]:
df_call_details

,callID,callDurationInSeconds,agentsGradeLevel,callType,callEndedByAgent
0,ageentsGradeLevel,97,A,Inbound,False
1,2,64,E,in-bound,True
2,3,100,C,in-bound,False
3,4,69,D,Outbound,True
4,5,96,D,Inbound,True
...,...,...,...,...,...
595,596,147,E,Outbound,True
596,597,90,A,in-bound,True
597,598,89,F,Outbound,True
598,599,146,D,Inbound,False
599,600,103,C,Outbound,False

In [5]:
def remove_special_charater(calltype):
    result= calltype.replace('-','')
    return result

In [6]:
df_call_details['callType']=df_call_details['callType'].apply(remove_special_charater)

In [7]:
df_call_details

,callID,callDurationInSeconds,agentsGradeLevel,callType,callEndedByAgent
0,ageentsGradeLevel,97,A,Inbound,False
1,2,64,E,inbound,True
2,3,100,C,inbound,False
3,4,69,D,Outbound,True
4,5,96,D,Inbound,True
...,...,...,...,...,...
595,596,147,E,Outbound,True
596,597,90,A,inbound,True
597,598,89,F,Outbound,True
598,599,146,D,Inbound,False
599,600,103,C,Outbound,False

In [8]:
df_call_log

,id,callerID,agentID,complaintTopic,assignedTo,status,resolutionDurationInHours
0,1,CALLER_1,163,Billing discrepancy,122.0,CLOSED,33.0
1,2,CALLER_2,133,Difficulty reaching customer support,NaN,new,NaN
2,3,CALLER_3,153,Wrong item received,122.0,resolved,NaN
3,4,CALLER_4,161,Unauthorized charges,151.0,pEnding,NaN
4,5,CALLER_5,148,Unprofessional behavior,NaN,new,NaN
...,...,...,...,...,...,...,...
595,596,CALLER_596,137,Unhelpful support,169.0,new,NaN
596,597,CALLER_597,159,Slow response time,NaN,resolved,NaN
597,598,CALLER_598,148,Shipping delay,150.0,pending,NaN
598,599,CALLER_599,161,Website not working,148.0,pEnding,NaN
599,600,CALLER_600,127,Wrong item received,149.0,resolved,NaN

In [9]:
df_call_log.shape

(600, 7)

In [10]:
df_call_log.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         600 non-null    int64
 1   callerID                   600 non-null    object
 2   agentID                    600 non-null    int64
 3   complaintTopic             600 non-null    object
 4   assignedTo                 372 non-null    float64
 5   status                     600 non-null    object
 6   resolutionDurationInHours  187 non-null    float64
dtypes: float64(2), int64(2), object(3)
memory usage: 32.9+ KB

In [11]:
df_call_log['status']=df_call_log['status'].str.lower()

In [12]:
df_call_log[df_call_log['resolutionDurationInHours'].isna()]

,id,callerID,agentID,complaintTopic,assignedTo,status,resolutionDurationInHours
1,2,CALLER_2,133,Difficulty reaching customer support,NaN,new,NaN
2,3,CALLER_3,153,Wrong item received,122.0,resolved,NaN
3,4,CALLER_4,161,Unauthorized charges,151.0,pending,NaN
4,5,CALLER_5,148,Unprofessional behavior,NaN,new,NaN
6,7,CALLER_7,179,Unsatisfactory resolution,125.0,resolved,NaN
...,...,...,...,...,...,...,...
595,596,CALLER_596,137,Unhelpful support,169.0,new,NaN
596,597,CALLER_597,159,Slow response time,NaN,resolved,NaN
597,598,CALLER_598,148,Shipping delay,150.0,pending,NaN
598,599,CALLER_599,161,Website not working,148.0,pending,NaN
599,600,CALLER_600,127,Wrong item received,149.0,resolved,NaN

In [13]:
df_call_log['resolutionDurationInHours'] = df_call_log['resolutionDurationInHours'].fillna(0).astype('int64')

In [14]:
df_call_log[df_call_log['assignedTo'].isna()]

,id,callerID,agentID,complaintTopic,assignedTo,status,resolutionDurationInHours
1,2,CALLER_2,133,Difficulty reaching customer support,NaN,new,0
4,5,CALLER_5,148,Unprofessional behavior,NaN,new,0
7,8,CALLER_8,171,Rude customer service representative,NaN,pending,0
14,15,CALLER_15,171,Slow response time,NaN,new,0
18,19,CALLER_19,159,Shipping delay,NaN,closed,32
...,...,...,...,...,...,...,...
583,584,CALLER_584,158,Shipping delay,NaN,pending,0
585,586,CALLER_586,154,Incorrect charges,NaN,closed,43
586,587,CALLER_587,139,Unauthorized charges,NaN,pending,0
594,595,CALLER_595,180,Difficulty getting a refund,NaN,new,0
596,597,CALLER_597,159,Slow response time,NaN,resolved,0

In [15]:
df_call_log['assignedTo']=df_call_log['assignedTo'].fillna('0').astype('int64')

In [16]:
df_call_log['resolutionDurationInHours']=df_call_log['resolutionDurationInHours'].fillna('not given')

In [17]:
df_call_log

,id,callerID,agentID,complaintTopic,assignedTo,status,resolutionDurationInHours
0,1,CALLER_1,163,Billing discrepancy,122,closed,33
1,2,CALLER_2,133,Difficulty reaching customer support,0,new,0
2,3,CALLER_3,153,Wrong item received,122,resolved,0
3,4,CALLER_4,161,Unauthorized charges,151,pending,0
4,5,CALLER_5,148,Unprofessional behavior,0,new,0
...,...,...,...,...,...,...,...
595,596,CALLER_596,137,Unhelpful support,169,new,0
596,597,CALLER_597,159,Slow response time,0,resolved,0
597,598,CALLER_598,148,Shipping delay,150,pending,0
598,599,CALLER_599,161,Website not working,148,pending,0
599,600,CALLER_600,127,Wrong item received,149,resolved,0

In [18]:
df_call_details.to_csv('cleaned_call_details.csv', index=False)

In [19]:
df_call_log.to_csv('cleaned_call_log.csv', index=False)